### ISSUE TITLE
updated article editor & article views

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#53]
summary of improvements/changes to the article editor:
(_new fields - and some of the other new features - will require updating the data model_ ([see updated ER diagram](https://etiennelebel.com/logos/curatescience_datamodel_v0.3.0.png) (entities to-be-added in blue))
  * improved organization & layout of input boxes (two-columns for viewports >1900px, everything fitting vertically within 1050px; stacked for viewports <1900px)
  * curation of several new fields (URLs to videos, talks/presentation slides, supplementary materials/appendices, and media coverage)
  * ability to add multiple URLs for preregistration, study materials, data, and code input boxes
  * ability to indicate reasons for non-transparency & new Basic 4/Basic 7 retroactive disclosure statements
  * DOI lookup metadata extraction (already implemented ([see here](https://github.com/ScienceCommons/curate_science/commit/6f03e62edc339dc78e411d54937d2933e6a5b559)), just needs to be plugged in/adapted)
![edit-article-two-columns](https://user-images.githubusercontent.com/4512335/58434540-33897780-808a-11e9-9e7c-ecc23082bb93.png)

**DETAILS:**
* the new sections "BASIC METADATA", "PRIMARY TRANSPARENCY", "SECONDARY TRANSPARENCY", and "MEDIA & ASSOCIATED CONTENT" are now grouped and spaced for better organization and visual distinctiveness
* certain fields are grey but enabled (e.g., citations, downloads, views, abstract, keywords, prereg type, reasons for non-transparency drop downs) vs. others are grey/disabled until required input is inputted (e.g., protected access check boxes)
* revert back to using proper Material UI text fields (i.e., [Outlined Textfields with placeholder and always-visible label](https://material-ui.com/demos/text-fields/#outlined) 
  * re-add text field adornments to applicable fields (i.e., [Outlined Input Adornments](https://material-ui.com/demos/text-fields/#outlined-input-adornments), see mockup above) (see older [ArticleEditor.jsx](https://github.com/ScienceCommons/curate_science/blob/c8e8e47161ebd430a59084bb54f2280ee92173b4/src/components/ArticleEditor.jsx) where this used to be implemented)
* new article type: "Original - Meta-research": display only Prereg (P), Materials (M), Data (D), & Code (C) badges within article editor and for article card view (see Card C in article views specs below; "Original - Meta-research" label native title: "Article reports new observations regarding a meta-research question") 
(Article type dropdown default remains "Original")
* new details input boxes for 2 article types:
  * Reanalysis - Reproducibility/Robustness: display "Original article/study" and "Original article URL" input boxes (both optional)
  * Commentary: display "Target article" and " Target article URL" input boxes (also both optional)
![2-article-type-details-input-boxes](https://user-images.githubusercontent.com/4512335/57281754-e24e1f80-70ab-11e9-8712-01db9280a708.png)
* reduce preregistration type radio buttons and radio button text so they can fit within prereg row
* multiple URLs for preregistration, materials, data, & code: these will be implemented as MD chip input components exactly as described for the Video URLs, Slides/presentation URLs, and Suppl. materials URLs within the Secondary Transparency section below (displayed as in mockup here)
![Untitled-1](https://user-images.githubusercontent.com/4512335/63331146-58ae1f00-c335-11e9-90db-2fb7f0139016.png)
* _protected access_: for materials and data (ONLY), if a valid URL is entered, the respective "Protected access" checkbox becomes enabled. if checked, the materials and data badge popups are displayed slightly differently than the normal case: "Materials" instead of "Public Materials" and "Data" instead of "Public Data", and the text "(protected access; login required)" to the right of each URL (displayed as in mockup here for Materials; same for Data; very rare edge case where "protected access" applies only to one of multiple URLs will be dealt with later)
![protected-access-view-example](https://user-images.githubusercontent.com/4512335/58582775-8a28ba00-8220-11e9-9977-86d542df241f.png)
* _reasons for non-transparency_: for materials and data, a "Reasons for non-transparency" dropdown is displayed. each dropdown only has 2 options ("Proprietary/IP" and "Ethical reasons"), and the default is blank. If a reason is selected (for either materials or data), a dark grey (#b5b5b5) unavailable badge is displayed and this reason is displayed on badge hover (displayed as in mockup; example text for Study Materials: "Study materials not available: Ethical reasons").  The default unavailable badge should be updated from #b5b5b5 to a lighter grey: #f0f0f0)
![content-unavailable-due-to-reason-view-example](https://user-images.githubusercontent.com/4512335/57310932-f6654180-70ea-11e9-9717-b0e7c092c339.png)
* Reporting standards improvements:
   * Reporting standards dropdown defaults to "Basic 4/Basic 7 (retroactive)" (as in mockup above) and should use the proper [Material UI Outlined Select text field](https://material-ui.com/demos/text-fields/#outlined) with "Reporting standards" as label.
   * details for the "Basic 4/Basic 7 (retroactive)" component:
     * [URL of Basic 4 (retroactive) details](https://psychdisclosure.org/) ; [URL of Basic 7 (retroactive) details](https://medium.com/@IGDORE/retroactive-disclosure-statements-make-the-past-more-useful-c1b2e73f4bae)
     * if "All details reported in article† (for all studies)" checkbox is checked, then the corresponding text field to the left becomes disabled
     * "Disclosure date" defaults to current date, but can be changed to a prior date (just a text field for now; later we'll implement a more proper date-picker component)
     * if user enters information (or checks checkboxes) for:
       * items 1 through 4, "Basic 4 (retroactive)" reporting standards compliance is achieved (and is displayed for the RS badge popup as in mockup immediately below; "Basic 4 (retroactive)" hyperlinked to this [URL](http://PsychDisclosure.org))
![basic-4-retroactive-view](https://user-images.githubusercontent.com/4512335/57312551-134f4400-70ee-11e9-9f75-d0847928e29f.png)
       * items 1 through 7, a "Basic 7 (retroactive)" reporting standards compliance is achieved (and is displayed for the RS badge popup as in mockup immediately below; "Basic 7 (retroactive)" hyperlinked to this [URL](https://medium.com/@IGDORE/retroactive-disclosure-statements-make-the-past-more-useful-c1b2e73f4bae))
![basic-7-retroactive-view](https://user-images.githubusercontent.com/4512335/57312575-1ea26f80-70ee-11e9-8099-0ccd18b23c17.png)

   * for the various *other* reporting standards, display the following:
     * Basic 4 (at submission; PSCI, 2014): as per this mockup ([details URL](https://www.psychologicalscience.org/publications/psychological_science/ps-submissions#DISC); check boxes checked and non-editable)
![basic 4 (at submission) info](https://user-images.githubusercontent.com/4512335/57311397-e13ce280-70eb-11e9-8be1-977685980ecc.png)
       * badge popup view:
![basic-4-at-submission-view](https://user-images.githubusercontent.com/4512335/57312615-37ab2080-70ee-11e9-8095-98cc355ff113.png)
     * MARS (2018): [Meta-Analysis Reporting Standards (APA's MARS; see Table 9)](http://www.apa.org/pubs/journals/releases/amp-amp0000191.pdf)
       * badge popup view:
![MARS-view](https://user-images.githubusercontent.com/4512335/57384633-3bec4200-71b1-11e9-883b-fe3f0c9e7f49.png)
(For the remaining reporting standards, badge popups are displayed the same as the MARS (2018) popup except with different reporting standards name, description text, & hyperlink of course)
     * CONSORT-SPI (2018): [Randomized trials of social and psychological interventions (CONSORT-SPI 2018; 26 items)](https://trialsjournal.biomedcentral.com/track/pdf/10.1186/s13063-018-2733-1)
     * CONSORT (2010): [Parallel-group RCTs reporting checklist (CONSORT 2010; 25 items)](http://www.consort-statement.org/media/default/downloads/consort%202010%20checklist.pdf)
     * JARS (2018): [Journal article reporting standards for articles reporting new data (APA's JARS; see Table 1)](http://www.apa.org/pubs/journals/releases/amp-amp0000191.pdf)
     * STROBE (2007): [Observational/correlational studies reporting checklist (STROBE 2007; 22 items)](https://www.strobe-statement.org/fileadmin/Strobe/uploads/checklists/STROBE_checklist_v4_combined.pdf)
     * ARRIVE (2010): [Animal research reporting checklist (ARRIVE 2010; 20 items)](https://www.nc3rs.org.uk/sites/default/files/documents/Guidelines/NC3Rs%20ARRIVE%20Guidelines%20Checklist%20%28fillable%29.pdf)
     * Nature Neuroscience (2015): [Life science neuroscience studies research checklist (Nature Neuroscience, 2015)](https://www.nature.com/authors/policies/reporting.pdf)
     * PRISMA (2009): [Systematic reviews/meta-analyses reporting checklist (PRISMA 2009; 27 items)](http://prisma-statement.org/documents/PRISMA%202009%20checklist.pdf)
     * PRISMA-P (2015): [Systematic reviews/meta-analyses reporting checklist (Updated PRISMA-P 2015; 17 items)](http://prisma-statement.org/documents/PRISMA-P-checklist.pdf)
* updates to Commentaries component as follows: 
  * display "Authors/publication year" and "Commentary URL" input boxes (and corresponding Delete icon) by default
  * "ADD COMMENTARY" button is replaced by an "add icon" to the right of the delete icon (with the following title text on hover: "Add additional commentary").  If an additional commentary is added, the add icon moves to the end of the new (2nd) commentary row (as implemented within the ["Edit Contact" component](https://contacts.google.com/?hl=en&tab=rC) of Google's Contacts product to add additional email address or phone number)
* "Add Figure" section remains unchanged for this contract, so this section can be ignored (except for adding new section text "MEDIA & ASSOCIATED CONTENT")
* Video URLs, Slides/presentation URLs, and Suppl. materials URLs input boxes are Material UI chip input components (see [here](https://teamwertarbyte.github.io/material-ui-chip-input/) and [MatChipInput](https://material.angular.io/components/chips/overview)) w/ trimmed text beyond 20 characters (similar to MD chip inputs of Gmail's email addresses field).  That is, user can copy-and-paste a URL (or type it), presses ENTER, and (deleteable trimmed) chip is created. Cursor then blinks to the right of the last chip so the user can enter another URL.  
   * for "Suppl. materials URLs", each URL will be displayed as "Suppl. materials # 1", "Suppl. materials # 2", etc. (light color given secondary importance)
   * Video URLs, Slides URLs, and Suppl. Materials URLs will be displayed as follows (a separate Video or Slides icon for each Video or Slides URL inputted (light color given secondary importance); see [article views live demo, first article card](https://etiennelebel.com/author/article-views.html) for Slides icon): 
![media-associated-content-view](https://user-images.githubusercontent.com/4512335/57386382-7dcab780-71b4-11e9-9fe9-71092da437f3.png)
* Media coverage: this component behaves and is displayed exactly like the "Commentaries" component (as described above), but with different text box and placeholder text. Media coverage URLs will be displayed as in mockup immediately above (if no Media coverage URLs are entered, the "News coverage:" text descriptor and entire line is hidden).
* info icon popups text:
  * Impact metrics & Full-text URLs: 
> Non-paywalled article full-text URLs only.  'HTML URL' means a URL to an HTML page of a full-text article, *not* a URL to the publisher's website (which is automatically linked in the DOI field).  Impact metrics should be curated from the content provider if available. Citation values should be taken from Google Scholar.
  * Article type (should probably describe all ATs within this popup!): 
> The 'Original' article type can also include articles that report a mixture of original and so-called 'conceptual replications', which are considered 'Far' or 'Very Far' replications according to our replication taxonomy. The 'Replication' article type also includes articles that report a mixture of original and replication studies (i.e., 'Close', 'Very Close', or 'Exact' replications according to our replication taxonomy). 
  * Preregistration: 
> A 'pregistration protocol' is the study protocol (methods protocol) that was preregistered prior to data collection.'
  * Materials: 
> 'Study materials' are all materials (e.g., questionnaires, stimuli, experimental files, etc.) that would be needed for an independent researcher to conduct a replication of a study (in open/open-source or proprietary file formats).
  * Data: 
> 'Data' are the minimal data set file(s), in raw or processed form, that are needed to reproduce an article's primary results.
  * Code: 
> 'Code' means any statistical analyses syntax files and/or code files that were used to conduct the statistical analyses and/or to generate figures or tables.
  * Reporting standards: 
> Choose the specific reporting checklist that you followed in reporting your study/studies (these are checklists of specific details that need to be reported for the type of study you conducted). For example, if you've conducted an animal study and reported the 20 items of the ARRIVE (2010) checklist, then you would select 'ARRIVE (2010)'. For psychology studies, you can retroactively affirm reporting standards compliance by choosing 'Basic 4/Basic 7 (retroactive)' and providing the information for the 4 (or 7) items (or by ticking the relevant check boxes to indicate that the item-specific information was reported in your article).

</br></br>
for both "Edit" or "New" article actions, editor will be loaded in an *improved* modal window:
 * has a sticky header at the top (like in Google Scholar, [example](https://scholar.google.com/citations?hl=en&user=REViqVUAAAAJ&view_op=list_works#d=gs_md_cita-d&u=%2Fcitations%3Fview_op%3Dview_citation%26hl%3Den%26user%3DREViqVUAAAAJ%26citation_for_view%3DREViqVUAAAAJ%3AWF5omc3nYNoC%26tzom%3D-120); so Save button is always visible for screen sizes smaller than 1050px)
 * reduced modal header height from 64px to 48px
![new-article](https://user-images.githubusercontent.com/4512335/58434589-764b4f80-808a-11e9-81c2-a5befd9717d2.png)

</br></br>
**Article views ([live demo](https://etiennelebel.com/author/article-views.html)) for the different article types** (in order):
* Card A: Replication (5 badges: P (preregistration), M (materials), D (data), C (code), R (reporting standards))
* Card B: Original (5 badges: P, M, D, C, R)
* Card C: Original - Meta-research (4 badges: P, M, D, C)
* Card D: Reanalysis - Meta-analysis (4 badges: P, D, C, R)
* Card E: Reanalysis - Reproducibility/Robustness (*or* Reanalysis - Meta-research; not displayed) (3 badges: P, D, C)
* Card F: Conceptual (bonus badges)
* Card G: Commentary (bonus badges)
![article-views](https://user-images.githubusercontent.com/4512335/57374202-a34ac780-719a-11e9-88b7-2c932354f2c8.png)

**Comment by mickaobrien** [comment]
@eplebel The editor mockup only has one 'Protected access' checkbox for the study materials and data URLs (rather than one checkbox per URL), should this be set for all URLs together i.e. if one URL is protected then they all are?

**Comment by eplebel** [comment]
correct
(this of course won't cover the very rare edge case where "protected access" applies only to one of multiple URLs, but this will be dealt with later)

and this limitation applies to the updated view as well whereby the "protected access; login required" text will appear to the right of *each* URL (even if it only applies to one of them)
![protected-access-view-example](https://user-images.githubusercontent.com/4512335/58582775-8a28ba00-8220-11e9-9977-86d542df241f.png)

**Comment by mickaobrien** [comment]
@eplebel I just pushed the bulk of the changes to [staging](https://curate-science-staging-2.appspot.com/app/). There are still a few outstanding issues (e.g. the popups for the reporting standards and the transparency badges, the input adornments) but most of the work for the editor screen itself should be done. Let me know what you think.

I had to upgrade a few libraries (react, material-ui and some related things) to get all the the outlined inputs working correctly so there were a few changes that had to be made to the code to account for this. Everything else _should_ be working as it was before but if you come across anything strange, let me know.

**Comment by eplebel** [comment]
awesome! overall things are looking good. 

i'm going to make a list of the major stuff still missing (or still not working, e.g. DOI LOOKUP doesn't appear to be working) pronto!

also, could you add the search results page functionality, as mentioned in this comment, thanks!:
https://github.com/ScienceCommons/curate_science/issues/55#issuecomment-521411596

**Comment by eplebel** [comment]
here's the list (i will try to add more details/mockups to some of these to avoid any ambiguities and save us time!):
- reduce height of all text fields as much as possible (to still fit the chips i guess, but even the height of the chips could potentially be reduced a little bit)
- only getting the correct 2 column layout when i zoom out to 80% (even though i have a 1920px display); a potential fix (that could kill 2 birds w/ one stone) is to shrink down the font-size of all text across the entire site (because since the jeremey's 1st version), i've found the font-size too large, and actually typically zoom out to 90% to make it look better. (i'm not sure if there's an easy way to reduce font-size of all text (keeping relative font-size of text fields w/ different font-size constant), but it's something worth considering...) 
- remove the horizontal scroll bar at the bottom
- remove the bottom "SAVE" and "CANCEL" buttons altogether (and entire row) given that both of these actions can already be completed in the modal header
- DOI LOOKUP doesn't appear to work (i.e., clicking "DOI LOOKUP" button doesn't populate the title, authors, publication year, and journal name for valid DOIs, eg 10.1016/j.jesp.2008.04.005)
- missing: input boxes for details of "commentary" & "Reanalysis - Reproducibility/Robustness" article types are missing (and the display of this info for the article type popup within article card (will soon move mockup of this here))
- missing: displaying protected access status for materials and data links (to the right of each link)
- fix: reasons-for-non-transparency dropdowns (for materials & data) should always be enabled
- missing: displaying non-transparent (dark-grey) exempt badges for materials & data (w/ corresponding title displaying the reason for the non-transparency); and correspondingly using a lighter grey badge for the default unavailable badge: "The default unavailable badge should be updated from #b5b5b5 to a lighter grey: #f0f0f0".
- disclosure date is not saving (it seems to always revert back to the article creation date)
- to simplify things, please remove the "Basic-4 retroactive; 2012)" reporting standard because it's already included in the "Basic 4/Basic 7 (retroactive)" reporting standard
- missing: reporting standards details for all reporting standards (except "Basic 4/Basic 7 (retroactive)")
	-simplification: for "Basic 4 (at submission; PSCI, 2014)", can just display following text (instead of more complicated UI spec provided):
	"All (1) excluded data (subjects/observations), (2) tested experimental conditions, (3) assessed outcome measures/dependent variables, and (4) the sample size determination (& data collection stopping rule) have been reported in the article (for all studies). Since January 2014, all authors submitting to the journal [Psychological Science](https://us.sagepub.com/en-us/nam/journal/psychological-science#description) have affirmed compliance to this reporting standard; see [details at the journal website](https://www.psychologicalscience.org/publications/psychological_science/ps-submissions#DISC)."
- missing: displaying reporting standards badge within article card (and popup displaying actual disclosed information)
- missing: the "commentaries" and "media coverage" components still need to be updated to the spec (text fields displayed by default, and a "+" button displayed at the right of the delete icon (for the last item only) to add additional commentaries/media coverage items
- missing: displaying the video URLs, slides/presentation URLs, supp materials URLs, and media coverage items within article card
- missing: all info icon popups within article editor

hopefully we can have prompt iterations for these given we're a bit behind schedule and was really hoping to be able to show contract#1 features to the team here in Leuven by begining of academic term in a few weeks, thanks!

**Comment by mickaobrien** [comment]
@eplebel Thanks for all of that, it clarified a lot. I was trying to sort out as many of the issues as possible yesterday because I won't be able to get back to this until next Wednesday. There are still a few left (and a few fixes to my fixes :smile:) but hopefully they won't take too long. And I haven't forgotten about the search box changes either, they're on the way!

**Comment by eplebel** [comment]
ok thanks for heads up. i will carefully review/test all contract #1 pages/features, and then make a list of all outstanding issues so that we can iterate as efficiently/promptly as possible upon your return!

**Comment by eplebel** [comment]
*final outstanding minor issues* (above & beyond what's mentioned [above](https://github.com/ScienceCommons/curate_science/issues/53#issuecomment-526539058)):

- [ ] add margin-top:-8px to 2nd & 3rd preregtype radio buttons (to save vertical space; see mockup below)
- [ ] remove "Reasons for transparency" header
	- [ ] also remove centered hyphen below it and entire corresponding div, so that the 1st preregtype radiobutton stays on one line (see mockup below)
	- [ ] for both materials & data non-transparency dropdowns: add default (non-selectable) placeholder text: "Non-transparency exemption:" (see mockup below)
- [ ] set min-width to publication year text field to avoid it being clipped for two-column layout
![ae-esthetic-tweaks](https://user-images.githubusercontent.com/4512335/64108433-0d582f80-cd7d-11e9-8a04-0f2fc7660a1f.png)

- [ ] move keywords textbox to the right of abstract text field (50/50 split; to save vertical space real-estate) (see mockup below)
- [ ] for prereg, materials, data, & code badge popups, add left-margin (or invisible placeholder image) for URLs w/out content provider icon (so that links line up when multiple links are available)
- [ ] multiple URL text fields improvements
	- [ ] prevent duplicate URLs from being entered (which i thought was default for MD-chips)
	- [ ] prevent chips from overflowing text boxes ([potential solution](https://stackoverflow.com/questions/52805504/single-line-horizontal-chip-list-in-material-angular-6): "...wrap all mat-chip elements in a div,  then add style display: flex to the div?
	- [ ] add the following placeholder text to all mutliple URL text fields : "Insert URLs & hit ENTER"  (as done [here](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20placeholder&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel))


- [ ] when adding additional commentaries/media coverage items, focus cursor in the 1st text field (i.e., focus cursor in "Authors/publication year" textbox when adding additional Commentaries; focus cursor in "Media source name" textbox when adding additional media coverage item).
- [ ] shorten "All details reported in article † (for all studies)" to "All details reported †" (to save vertical space)
	- [ ] and update corresponding footnote text to: "† All details reported in article (for all studies) or reported in a public/non-paywalled preregistration protocol or supplementary materials linked herein (URLs to these linked materials must be provided in the relevant fields)."
	- [ ] only display "All details reported †" text  for the "Basic 4/Basic 7 (retroactive)" reporting standard (i.e., hide it for all other reporting standards (eg PRISMA, CONSORT, etc. ) because it's not relevant)

- [ ] under peer review: 
	- [ ]  clicking "Under peer review" disables the "Journal name" text field (sorry i overlooked this)
	- [ ]  display "Under peer review" as journal name if "Under peer review" checkbox is checked (sorry i forgot to mention how this would be displayed in the spec!);

**Comment by eplebel** [comment]
great work on latest batch of commits, it's really coming together! (https://github.com/ScienceCommons/curate_science/compare/20945eca03...e444964d34 and https://github.com/ScienceCommons/curate_science/compare/e444964d34...860870803d). everything is working as expected. only the following 3 minor issues were identified:
- max-width of popups no longer seem to be applied; max-width of all popups should be ~450px, to avoid excessively wide popups that are difficult to read: e.g., reporting standards badge popup; replication article type details popup, see screenshot below:
![Untitled-1zzzzz](https://user-images.githubusercontent.com/4512335/64524948-f9be4300-d2ff-11e9-86bf-f41cd5152fbc.png)

- within Reporting Standards (RS) badge popup, clicking "More" for truncated text reveals the truncated text, but then clicking anywhere else on the popup -- makes the popup disappear and reload (which means revealing truncated text for a 2nd "more" is very tricky/confusing because one has to click it twice and let it reload (and then the same problem for clicking on a 3rd more, etc.)

- all links should open in a new window (current behavior for all non-internal links), i.e. links to videos, talks/presentations, supplemental materials, replication target article URLs, commentary target article URLs, reproducibility/robustness reanalysis target article URL, reporting standards details URLs (within article editor and within reporting standards badge popup), etc. (sorry i guess i could/should have been clearer/more explicit about this)

after these are addressed, we're basically almost there. i'd say next critical items are as follows (we could potentially punt on the remaining minor issues):

- missing: all info icon popups within article editor (see above for actual text)
- for all new multiple URL text fields and Commentaries "Commentary URL" and "Media coverage URL" text fields , attempting to save invalid URLs yields incorrect "[object Object]" error message
- prevent chips from overflowing text boxes (potential solution: "...wrap all mat-chip elements in a div, then add style display: flex to the div?"
- place article page content inside a paper card (same style, padding, etc. as article list article card) (https://github.com/ScienceCommons/curate_science/issues/56#issuecomment-527072696)

**Comment by mickaobrien** [comment]
@eplebel I've pushed a bit of a fix for the issue with expanding the text in the popup. It's still not correct though because if a there's a lot of expanded text the position of the popup is likely to move a lot to fit it all in. One possible solution is to have the popups appear only when the badge is clicked and disappear when the user clicks away. That's not ideal though, I know. Just wanted to let you know the story with it.

**Comment by eplebel** [comment]
ok, if you can address the overflowing chips issue, i think we can call it done!  

once that's done, we could then push everything to the master branch, but perhaps we can try to coordinate a rough time, so i can be at the ready in case anything goes wrong (given lots of major changes are going through??)...

**Comment by mickaobrien** [comment]
Great! I had a look at the overflowing chips the other day and it was trickier than I expected, but I should be able to sort something out later today hopefully. I'll push it to staging for you to have a look and once you're happy with that we can push to master, maybe early tomorrow if that suited you?

**Comment by eplebel** [comment]
sounds good re: overflowing chips, and re: pushing to master tomorrow morning!

**Comment by mickaobrien** [comment]
Just pushed a fix for the overflowing chips to [staging](https://curate-science-staging-2.appspot.com/app/). Let me know what you think.
